name: flutter_grpc_demo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_p2p_plus:
    git:
      url: https://github.com/JAICHANGPARK/flutter_p2p_plus.git
      ref: main

  permission_handler: any
  lottie: any
  shared_preferences: any
  freezed_annotation: any
  json_annotation: ^4.5.0
  go_router: ^3.1.0

  flutter_riverpod: ^2.0.0-dev.5

  fluttertoast: any
  grpc: any
  protobuf: any

  pushable_button: any

  roslibdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: any
  freezed: any
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/

